### ISSUE TITLE
Rework Launcher/Login Screen

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#1]
The Username/Password prompt is obsolete as only guest logins are allowed. Skipping it completely or re-enabling the user database would make it more intuitive.

**Comment by eYeWoRRy** [comment]
Ah here it is - I fixed that one - but I cannot push it.

**Comment by PhilippvK** [comment]
Oh, did you add a database connection or have you removed the login screen?

(I am actually working on setting up a heroku mongodb for a few hours now)

**Comment by PhilippvK** [comment]
You have to fork this repository and then create a pull request.

**Comment by eYeWoRRy** [comment]
Removed the Password box 😝
