### ISSUE TITLE
Custom Maps - Buggy and some strange names

### ISSUE THREAD

**Issue by eYeWoRRy** [PhilippvK/playforia-minigolf#11]
Any kind and custom only is not working.
And the track names of customs folder include names like "Nazi" and "Penis"...
mhm not family friendly 🤷🏻‍♂️😝

**Comment by PhilippvK** [comment]
Thanks for reporting this. I will have a look at it.

Please be aware if the fact, that I am not the original creator of the source code and track names

**Comment by PhilippvK** [comment]
I removed all custom tracks in 24deaf86c48db37deccd80a4e3265cd7b79a4a0d.
