### ISSUE TITLE
Create new Release

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#115]
Version 2.2.0 would make sense

**Comment by allixx** [comment]
Hey, thanks for cutting the release!

However, is it intentional that release's assets are versioned 2.1.2.0?

**Comment by PhilippvK** [comment]
@allixx Good catch! Haven’t done a release in a few years and forgot to commit the changed Maven files before creating the tag. Release v2.2.1.0-BETA is currently being processed and should be up soon. I will remove the 2.2.0 release after the new one is available!
