### ISSUE TITLE
Multiplayer room name with blank space not working

### ISSUE THREAD

**Issue by eYeWoRRy** [PhilippvK/playforia-minigolf#12]
If you create a multiplayer room with a blank space e.g. "Friends Round" the screen freezes at "One moment...."

Server running on Linux. Have to check the log for more information.

**Comment by PhilippvK** [comment]
I have to debug this behavior to find out what’s happening.

Might be trivial, but I do not have much spare time for the following weeks/month.

**Comment by PhilippvK** [comment]
Hey, I have updated the regular expression for the server name and password to allow almost every special character (except `-`).

However there is no error handling yet.
