### ISSUE TITLE
Improving Client Channel Handling

### ISSUE THREAD

**Issue by wizbright** [PhilippvK/playforia-minigolf#13]
https://github.com/PhilippvK/playforia-minigolf/blob/6f1db0a182d5d959cb1735c3d5835d6707a9d9c9/server/src/org/moparforia/server/net/ClientChannelHandler.java

Line 21 is from the prior author I'm sure but it would be worth fixing since it shows up when packets are received.

**Comment by PhilippvK** [comment]
Thank you very much for noticing. I am on it...

**Comment by PhilippvK** [comment]
Done. (See 9bbba272a8f363fda8b8fce9a40967558ca36e25)
