### ISSUE TITLE
[Question]Running the game on a webserver

### ISSUE THREAD

**Issue by gudeb0b** [PhilippvK/playforia-minigolf#15]
Do you have any idea how to run the game on a current webbrowser?
i tried it with CheerpJ and the client-gui starts but fails when loading resources from the server ( both installed on a raspberry pi )

Thx for your work though. I tried it with friends over the internet and it worked well. Didnt manage to get it going for mac users though. 
In general it would be easier to use i think.

**Comment by PhilippvK** [comment]
Unfortunately Java in Browers is dead. In the past I have used an old version of Firefox with auto-updates disabled (which is a very bad idea in terms of security)

**Comment by PhilippvK** [comment]
> Didnt manage to get it going for mac users though.

I am running it flawlessly on macOS. May I ask what the problem was?

**Comment by gudeb0b** [comment]
For the win-users i just let them install latest java and execute a batch file which points to java with the standard installation path and the ip to my game-server. 
really dont know much about macOS and couldnt provide an equivalent to the batch file.
what would be the easiest way to start the client on macOS and connecting to a remote server?

**Comment by PhilippvK** [comment]
@gudeb0b  Potentially a bash script `minigolf.sh` containing f.e. `java -jar client.jar 192.168.1.13` which can be made executable by running `chmod +x minigolf.sh`. Then it should be executable via `./minigolf.sh` or via a double click in the finder. You might have to use absolute paths to java depending on the installed versions of it. `which java` might help you.

**Comment by alexvoedi** [comment]
I've got it running on my root server insider a Docker container.

**Comment by PhilippvK** [comment]
@alexvoedi Thanks for your explanation. Do you want the server to be publicly accessible for everyone who wants to use it or just for private use?

**Comment by alexvoedi** [comment]
@PhilippvK I prefer not to, sorry.

**Comment by PhilippvK** [comment]
Feel free to try of the latest update (version 2.0.0) of the client. It has a server ip for a game server I recently set up preconfigured. Feels free to let me know how the experience is.

https://github.com/PhilippvK/playforia-minigolf/releases/tag/v2.0.0
