### ISSUE TITLE
Merge upstream with forks

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#16]
I was quite happy when I found out that there was actually some work done on forks of this repository.

- @TheBigElmo (https://github.com/TheBigElmo/playforia-minigolf)
- @phibo22 (https://github.com/phibo22/playforia-minigolf)

As some stuff is starting to diverge I would like to merge the forks to continue working on the same codebase.

Do you (two) have any arguments against this?

**Comment by phibo22** [comment]
No worries, feel free to merge my stuff 👍

**Comment by flying-aces-hb** [comment]
Why was this closed without merges? I saw that phibo increased the number of players to 10 in his fork, do you think that part could be merged in? (commits from April 2)

Or do you want me to create a separate issue for that?

**Comment by PhilippvK** [comment]
Hi @flying-aces-h,

I do not remember exactly why I closed this but the unreliable server-client communication was probably part of the reason.

I will try to integrate the following changes into latest codebase until next week but as I can not really test the game with many players, help would be appreciated.

- [ ] Docker image support 
- [ ] Remove Dual Game
- [ ] Increase Player Limit

**Comment by flying-aces-hb** [comment]
Sure thing, I'm currently hosting a server at vps.saviola.de and the guys are playing almost every night atm with 4+ players. I'll keep an eye on the repo and distribute updated clients once you push new stuff.

**Comment by PhilippvK** [comment]
Thank you for your feedback.

May I ask you which Clients your guys are using? (JAR, EXE (Using Windows Installer) or self-compiled)

We had a huge restructuring regarding the build toolchain the the releases, so it would be good to know which ones of them are required.

**Comment by flying-aces-hb** [comment]
Apart from me they are all on Windows using the EXE, I'm using the JAR on Linux. But I don't mind building the clients for them until your next release comes out.

**Comment by PhilippvK** [comment]
See #59 !
