### ISSUE TITLE
Bad word filter

### ISSUE THREAD

**Issue by maitovelkkis** [PhilippvK/playforia-minigolf#17]
Fix and re-enable the bad word filter. It really was part of the experience...

**Comment by PhilippvK** [comment]
If I remember correctly, I had to get rid of if because the encoding of the source files was completely screwed up.

Do you think you could have a look into it yourself?

**Comment by maitovelkkis** [comment]
I'll try when I have time, but not promising any results :P

**Comment by PhilippvK** [comment]
I think the encoding problems have just been related to IntelliJ IDEA, but I do not use it anymore. it build fine with the BadWordFilter enabled, but I did not manage to trigger the Filter in the lobby. I have no idea what could be causing this.

**Comment by PhilippvK** [comment]
I think i got the replacement of forbidden characters working but no success yet for “badwords”

**Comment by PhilippvK** [comment]
i figured it out.

**Comment by maitovelkkis** [comment]
How do I use it? I can still swear all day long. Do I have to add the bad words to some list?
Such a chore trying to figure out the code when names of the methods and variables seem to be auto generated.

**Comment by PhilippvK** [comment]
First, you have to checkout the master branch and compile it by yourself using ant, as I have not created a new tag, yet. (I assume you already did this.)

It seems like the BadWordFilter is only applied to incoming messages. I do not remember how it was implemented originally, but I think you could change is behavior by changing the if condition in the function `method86` in `client/src/com/aapeli/multiuser/ChatTextArea.java`.

The Bad Words and Nicks are read from the`res/l10n/en_US/Shared.xml` file. Please note that they are inserted in a reversed order. I also do not know if the other locales are also used in some way. There are not may entries, so I do not know if it reflects the behavior of the original filter in any way.

Yeah, as most of the code was decompiled for the original JARs somehow, understanding what is going on is very annoying, especially for the BadWordFilter.

**Comment by maitovelkkis** [comment]
Thanks for pointing to the right direction. Tested with 2 clients now and it does indeed work. I don't remember how it used to be either.

I was happy to see that there is the Finnish localization file too, as that's the language I used to play it in.

**Comment by PhilippvK** [comment]
> I was happy to see that there is the Finnish localization file too, as that's the language I used to play it in.

I think `en_US` is configured as the default locale somewhere in the Client Source code. Maybe it would be worth trying out changing that setting to `fi_FI`.

**Comment by maitovelkkis** [comment]
> I think `en_US` is configured as the default locale somewhere in the Client Source code. Maybe it would be worth trying out changing that setting to `fi_FI`.

Yes, managed to change the language by changing these lines in launcher.java.
`            params.put("locale", "en");
            params.put("lang", "en_US")`
