### ISSUE TITLE
Tracks symlink doesn't work on windows 10

### ISSUE THREAD

**Issue by maitovelkkis** [PhilippvK/playforia-minigolf#19]
I have to delete the tracks symlink file and move the tracks folder to server folder for the server to start. Does the tracks folder need to be in the root folder?

**Comment by PhilippvK** [comment]
The tracks directory has to be in the same directory where the `server.jar` is executed. Depending on your OS a symlink mal work or just copy it over. I did not packaged it into the JAR archive to be able to add tracks more easily in the future.

My plan is to (optionally) swap back to a DB based track registry. I am already working on this but I would not expect something before summer.

However I will add an information for Windows Users to the README about how to handle the symlink.

For people who just want to play the game I recommend to download the released jar files and unzip the tracks archive where you want. A docker container image will also be provided at some time to make hosting easier.
