### ISSUE TITLE
readme is wrong

### ISSUE THREAD

**Issue by tw0f1sh** [PhilippvK/playforia-minigolf#24]
just to let u know your parameter inside the readme is wrong for the build

u wrote: 

> java -jar client.jar **-server 192.168.1.7** -lang en_US # Replace IP with the one of your server (which you can find out by using for example `ifconfig`/`ipconfig`) and lang with en_US, fi_FI or sv_SE

but instead of **-server 192.168.1.7** u need to remove the **-server** parameter

correct way:
 java -jar client.jar **192.168.1.7**

otherwise it connects to http://-server/Shared/sound/
screen: https://www1.xup.in/exec/ximg.php?fid=12240422

**Comment by PhilippvK** [comment]
The latest release was older than the version on the master branch. Sorry for that. I just published a new release which will be available soon.

You can expect to find Standalone build for windows and macOS starting tomorrow with the release of `v2.0.0`.

**Comment by PhilippvK** [comment]
@tw0f1sh 

Here you go: https://github.com/PhilippvK/playforia-minigolf/releases/tag/v1.4

I have recently set up a very low-spec game server hosting the minigolf game (`135.209.2.60`)

If you get the chance to try it out, I would be happy if you would provide feedback.
