### ISSUE TITLE
Is there interest in a complete reimplementation?

### ISSUE THREAD

**Issue by alexvoedi** [PhilippvK/playforia-minigolf#26]
With enthusiasm I realize that many others besides myself are interested in helping the well-known miniature golf to new life. I appreciate the work you have put into this project.

But what do you think about doing a complete reimplementation of the game instead of refactoring it (which will be quite difficult, especially on the client side), where (if I interpreted the source code correctly) the calculation of the physics is not done on the client side but on the server side, with modern technologies, a database that records various statistics of the games, responsiveness and independence from the operating system, possibly with achievements? 

Of course, the whole thing would then be a community project and not a one-man job. Before I found this repository, I was already working on a reimplementation of the game in Javascript using Colyseus (see https://colyseus.io/) and Planck.js (see http://piqnt.com/planck.js/).

Is there any interest on your part to put such a project into action?

**Comment by PhilippvK** [comment]
I was already thinking about this.

However have no interest in implementing such a complex project from scratch nor would I like to take over the responsibility for the development.

If there are many contributors who also want to do this, I would be happy to help somewhere but as I am actually an Embedded Engineer, I do not really like working with such high level languages and also can not afford to invest much time in such a project.

Anyhow I would like to leave this open to give everyone how wants to take part has the chance to let you know. It would be great if you are able to find some support to make your idea reality.

**Comment by alexvoedi** [comment]
I think this can be closed since there is not interest.
