### ISSUE TITLE
Sounds aren't working

### ISSUE THREAD

**Issue by maitovelkkis** [PhilippvK/playforia-minigolf#28]
Can't hear any effects at least on my Windows 10 PC. Not a big deal but would be nice.

**Comment by PhilippvK** [comment]
I have to try out if the sound is broken on every distribution. Do you know if sound was working fine with version v1.3 and before?

**Comment by maitovelkkis** [comment]
It has never worked for me but I don't know what versions I have used...
________________________________

**Comment by PhilippvK** [comment]
Well, after some research I found out that there is not supposed to be any sound except the notification "beep beep" when someone challenges you in the lobby.

The `res/agolf/` directory does not have any sounds in it. Just the `shared` ones are loaded in `client/src/com/aapeli/client/SoundManager.java`. To be honest I am not sure anymore if there have been sound during the gameplay of the latest version of the minigolf game.

There are in fact ball sounds and a few special effects in the `agolf2` (Super Minigolf) directory. So if you would like to load and play them in a original minigolf session, feel free to try it out, but be warned that reading the code related to the SoundManager is not very enjoyable as almost every variable name is cryptic.

**Comment by pehala** [comment]
It seems like there were never sounds in `agolf` game, only in `agolf2`.

**Comment by maitovelkkis** [comment]
I could swear that there was some kind of hitting Ball sound effect when I played it on Aapeli, but I could be wrong too...

**Comment by PhilippvK** [comment]
I imagine the only sound which was existent in the minigolf game was in the lobby when someone challenges you. Maybe sound has been added at a later point but I am also not sure.

**Comment by StenAL** [comment]
I fixed this in https://github.com/PhilippvK/playforia-minigolf/pull/103.
