### ISSUE TITLE
Server Shutdown

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#32]
As I can take the responsibily for any hate speech and racism happening of the minigolf server, I am forced to shut down the server application.
I am very thankful for more than 300 logins and about 20k strokes over the last month, even if it was never profitable for me. I really hope, you've been able to enjoy the game at least a single time.

For playing in the future, you have to setup a server on your own.

**Here are a few tips to get started:**
- Setup a free Google Cloud Compute Engine Instance (f1-micro, See: https://cloud.google.com/free)
- Host the server on a private computer/server via port forwarding (f.e. Raspberry Pi)
- Create a virtual network with your friends (for example using LogMeIn Hamachi) to run the server on-demand
- ...

**Comment by General-crypto** [comment]
hi dude, how does it work with the aimbot? i really don't know to activate it...

**Comment by PhilippvK** [comment]
@General-crypto 
The ambit is disabled by default and can be enabled by changing line 65 of `client/src/agolf/game/GameCanvas.java`.

After this, you need to recompile the client using `ant compile` in the `client` directory. After this, the ambit mode can be toggled on/off just by pressing `C`.
