### ISSUE TITLE
Migrate to a better build system

### ISSUE THREAD

**Issue by pehala** [PhilippvK/playforia-minigolf#35]
While the current Ant system works, I think it would be a good idea to migrate to a better build system like Maven, which would enable things like proper dependency management and not depend on hardcoded jars stored at GitHub and also compiling all artefacts with one command from the root directory.

**Comment by pehala** [comment]
Hey @PhilippvK, I wanted to ask if this is something you would like to see. I would code it myself and then submit PR but I wanted to discuss it beforehand.

**Comment by PhilippvK** [comment]
Hello and thanks for your proposal.

Getting rid of Ant would be very great in my opinion. I unfortunately never had the time to do a migration by myself.

I would appreciate if you try to build the project using maven and am looking forward to a PR. 

In my opinion it is very important that the Travis CI Setup stays functional. (At least the generation of JAR files and Releases) Optionally it would be great if the building of windows/macos installers (see `distributions` branch) would still be possible (preferably also over CI)

I am happy to help with the CI/Installer part if I csn find time but to make things easier, I would recommend you to take the `build_dist.xml` Antfile from the mentioned branch as a base for the migration.
