### ISSUE TITLE
Add Docker image support

### ISSUE THREAD

**Issue by pehala** [PhilippvK/playforia-minigolf#46]
We should add the ability to build docker images for our artefacts.
- [x] Server Image
- [x] CI integration
- [x] Release tags in quay

**Comment by pehala** [comment]
Now the questions is how we want to do it, creating Dockerfile is trivial (except for potential problems with GUI in containers), but the problematic part is the publishing.

* Do we want to build the image in package phase? 
    * This would mean no one can do `mvn install` without having docker installed
    * Another solution would be to use custom goal with the need to supply it with credentials and repo to upload it to.
* Do we want maven solution of GitHub actions solution?
    * Both of them can build the image and upload it.
    * Maven solution has an advantage that we can build images on local machines.

**Comment by PhilippvK** [comment]
I would prefer the option of using GitHub actions for publishing the image. `mvn install` should not require Docker. Also I do not think that a custom maven command is required as building the image locally in a manual way is not difficult.

**Comment by PhilippvK** [comment]
@pehala Do we want to publish the Docker Image to Docker Hub? Are there any concerns against that in terms of copyright issues?

**Comment by pehala** [comment]
That is the question, I am not sure about distribution rights and code rights, if we don't want to publish it tho, there is not way of even implementing it.

**Comment by pehala** [comment]
On the other hand, we already distribute binaries in form of .jar and such on GitHub so docker hub isn't that much different from what we are already doing.

**Comment by PhilippvK** [comment]
Yep. So I think we should not care too much...

**Comment by pehala** [comment]
@PhilippvK Do you want me to also create github actions to automatically release the image?

**Comment by PhilippvK** [comment]
Feel free to do so, if you want!

**Comment by pehala** [comment]
Opening this up again as I found out we don't need special github CI for this, we can release this automatically on quay.io on each push/tag. I can set it up either under my account (e.g. sprtcz/minigolf), or we can set up custom organization for this (e.g. minigolf/server).

**Comment by PhilippvK** [comment]
Both is fine for me. If you don't mind just host it under your account.

**Comment by pehala** [comment]
Seems like I will need admin right to this repo as the quay will add webhook and access key automatically.

**Comment by PhilippvK** [comment]
I can also try to take care of it if you tell me the required steps 😊

**Comment by pehala** [comment]
Go on quay.io, create account and create new repository, quay should tell you about rest of it.

**Comment by PhilippvK** [comment]
Regarding Build Triggers: Master Branch only?

**Comment by pehala** [comment]
For now yes

**Comment by PhilippvK** [comment]
@pehala https://quay.io/repository/philippvk/minigolf/build/34889b71-5cbe-44b1-bc23-b20a34a952a6

**Comment by pehala** [comment]
Yeey it seems that it passed: quay.io/philippvk/minigolf:latest

In the future we might also add trigger for release tags, but I think master will do for now.

**Comment by PhilippvK** [comment]
Should I mention how to pull it in the main readme or somewhere else?

**Comment by pehala** [comment]
Sure, why not. It is still experimental but we will solve that problem when we do the release.

**Comment by PhilippvK** [comment]
Done! Should we leave this issue open?

**Comment by pehala** [comment]
I have added another goal to this issue, which is adding the trigger for release tags, not sure if the current one will work.

**Comment by PhilippvK** [comment]
<img width="886" alt="Screenshot 2021-01-11 at 09 32 45" src="https://user-images.githubusercontent.com/7712605/104159686-1553c500-53f0-11eb-83bb-339167ba0559.png">

Was this what you expected @pehala?

**Comment by pehala** [comment]
That actually is exaclr what I meant, perfect . We will see how it will work when we actually release something
