### ISSUE TITLE
question about other playforia games

### ISSUE THREAD

**Issue by okass** [PhilippvK/playforia-minigolf#54]
sorry the pull request isnt directly related to minigolf but I was wondering do you know any place that might have archived rest of the games? like for example defence or bombermania?

**Comment by PhilippvK** [comment]
@okass Unfortunately you are out of luck. The server part of most of the games is not available, so a complete redesign would be required.

There are some community-projects related to old Playforia games...  you probably want to check out this Discord Server for more information: https://discord.gg/tqZGmg

**Comment by okass** [comment]
thanks ill look into it

**Comment by Xele10** [comment]
Please can you send the discord link again or somewhere to communicate to us, has the link expired?
I was looking for a backup of the playforia games, especially the bombermania, defense and 8 ball

**Comment by PhilippvK** [comment]
Here is a 24h valid link for the mentioned discord channel: https://discord.gg/pRBmdd5A

They are reimplementing the Dogfight Game and managed to receive the actual source code from the company which owns it for using it as a reference after reaching out to them many times.

The problem with reviving the games you mentioned is, that the server.jar files which are essentiall for running the game are missing. I should have some sources/assets for the Pool and Canon Game Client but as far as I know they are useless...

**Comment by Xele10** [comment]
> Here is a 24h valid link for the mentioned discord channel: https://discord.gg/pRBmdd5A
> 
> They are reimplementing the Dogfight Game and managed to receive the actual source code from the company which owns it for using it as a reference after reaching out to them many times.
> 
> The problem with reviving the games you mentioned is, that the server.jar files which are essentiall for running the game are missing. I should have some sources/assets for the Pool and Canon Game Client but as far as I know they are useless...



Thanks for answering so quickly and kindly. Thank you and happy new year

**Comment by NGC224-Andromeda** [comment]
> Here is a 24h valid link for the mentioned discord channel: https://discord.gg/pRBmdd5A
> 
> They are reimplementing the Dogfight Game and managed to receive the actual source code from the company which owns it for using it as a reference after reaching out to them many times.
> 
> The problem with reviving the games you mentioned is, that the server.jar files which are essentiall for running the game are missing. I should have some sources/assets for the Pool and Canon Game Client but as far as I know they are useless...

Hi. I am curious if it's still alive, can you link another invite if it's still feasible. I am also really into getting back playforia bombermania.

**Comment by PhilippvK** [comment]
@NGC224-Andromeda These are the two Playforia-related discord channels I know:
- https://discord.gg/KA6pHjzu
- https://discord.gg/58zVdhCZ

However, I am not aware of any efforts related to Bombermania yet. It was an awesome game though.

**Comment by PhilippvK** [comment]
@twhatt22

https://discord.gg/mCG46K3n
https://discord.gg/SpSXCyRR
https://discord.gg/c8vUf4JX

**Comment by ilp0** [comment]
@PhilippvK would you create an invite for me as well? I would be interested to join.

**Comment by PhilippvK** [comment]
> @PhilippvK would you create an invite for me as well? I would be interested to join.

https://discord.gg/3mqbTRMVt

https://discord.gg/p8gp4Tqzh

https://discord.gg/A8zKnxH6X
