### ISSUE TITLE
Chat message visibility issue

### ISSUE THREAD

**Issue by flying-aces-hb** [PhilippvK/playforia-minigolf#57]
Hello,

when we are playing, the ingame chat (working fine in the lobby) seems broken in that not all other player's messages are displayed. E.g. player A and player B can see what each other write, and player A can see player C but not the other way around, while B can't see C and D can't see anyone else. This is just an example, who can see whom seems random and inconsistent.

Is this a known issue? Sorry if my description is convoluted, I couldn't think of a simpler way of describing the problem.

**Comment by PhilippvK** [comment]
As the server reimplementation is written in a highly unreliable way, there are many similar issues regarding chat, timing,... which are not easy to fix without throwing away everything and starting from scratch.

The buggy connection was partly covered here and I spend some time debugging and I temporarily inserted synchronized code section unfortunately without success:

#29

Any information which could help to find the exact code parts which are causing the chat issue would be very helpful.

**Comment by PhilippvK** [comment]
Yey, I found that silly chat bug.

The foreach loop for iterating over every player had a break statement in it.

I will push the fix later!
