### ISSUE TITLE
Rewrite Track handling

### ISSUE THREAD

**Issue by pehala** [PhilippvK/playforia-minigolf#61]
As part of #37, I would like to rewrite how the Tracks and Stats work.

This issue is to track (no pun intended) discussions surrounding this topic.

**Comment by pehala** [comment]
Part of the rewrite is separate Track statistics into their own class. I have extracted this but to be honest, I don't understand all of the statistics that are currently in use (or were on Playforia).
```java
public class TrackStats {

    private Track track;

    private int totalNumberOfAttempts;

    private int totalStrokes;

    private int bestPar;

    private int numberOfBestPar;


    private String firstBestPlayer;

    private long firstBestTime;

    private String lastBestPlayer;

    private long lastBestTime;

    private int[] ratings;
}
```
I am not sure about the use case for `lastBestPlayer`, is it used somewhere in the UI? Also are there any more statistics you want to track?
@PhilippvK

**Comment by PhilippvK** [comment]
The UI on Playforia had shown the first player who scored the highscore in all time the the last player who was able to finish the same number of strokes. If I remember correctly...

No need to show something else, the UI is already overloaded but if you or anyone else has a good idea, feel free to implement it.

**Comment by pehala** [comment]
Does it still show in this version? There is best stroke and by who, but I do not know if it also shows the lastPlayer who scored it.

**Comment by PhilippvK** [comment]
![image](https://user-images.githubusercontent.com/7712605/95688370-0e0ef680-0c0a-11eb-9cd7-ddb9a65e563c.jpeg)

I have not checked the current version of the game as I am currently not on my computer but this is what I found on Google. Its in German, but there are also screenshots in other languages.

I can see 2 different usernames and timestamps there. To be honest, I would not have anything against getting rid of one of them.

**Comment by pehala** [comment]
Thanks! I will remove the lastPlayer then, only fastest deserve the glory :D

**Comment by PhilippvK** [comment]
One thing which would be great, is allow resetting the highscores of all tracks in a easy way. Most of the highscores are unrealistic because they have been achieved using the aimbot (See #62), so the efforts in reenabling the highscore database would be quite useless as the score can not be beaten anymore.

**Comment by pehala** [comment]
Current plan is to start with blank database as default, but providing option to import scores from the files. In this case we dont have to do anything to reset it.

**Comment by pehala** [comment]
Another question, do we want to allow rating once per user, or once per game?

**Comment by PhilippvK** [comment]
I do not mind very much. Once per user seems to be more realistic but could be harder to handle, especially as there is no user-database.

**Comment by pehala** [comment]
We also have bestTime parameter, which I guess should be date instead?

**Comment by PhilippvK** [comment]
Ok!
