### ISSUE TITLE
Add Category line into track file format

### ISSUE THREAD

**Issue by pehala** [PhilippvK/playforia-minigolf#64]
Currently, the tracks are located in a subdirectory based on their category, this means that if you want the track in multiple categories you have to duplicate files. I think we should add category as a field into tracks to remove duplicates.

Just for the reference, from the 3178 tracks currently loaded, there are around 1500 duplicates.

**Comment by PhilippvK** [comment]
Oh wow. I was always wondering why there are soo many tracks 😅 Thanks for working on that!
