### ISSUE TITLE
Right mouse click behavior change

### ISSUE THREAD

**Issue by saviola777** [PhilippvK/playforia-minigolf#72]
Hello, we are using the 10 player version from #59 and one of our players noted that the right-click behavior changed from version 2.0.1, it now simply has the same effect as left click, where it previously change the shooting direction by 90° with each click (useful when close to the edges of the window). Was this an intentional change?

**Comment by PhilippvK** [comment]
@saviola777 Hey. The code for the features (Aim-Lines) has never changed. I think you just missed up the key combination.

The function can be toggled via the Meta-Key (on normal keyboards probably CTRL) as this code snipped suggests:

```
public synchronized void mousePressed(MouseEvent event) {

        if (this.gameState == 1) {

            if (event.isMetaDown()) {

                this.keyCountMod4 = (this.keyCountMod4 + 1) % 4;

                this.repaint();

            } else {

```

**Comment by PhilippvK** [comment]
May I ask if you have enabled the aimbot?

**Comment by saviola777** [comment]
`Ctrl` works to toggle through the modes, thanks.
