### ISSUE TITLE
Fix issue with case-insensitive track-filenames

### ISSUE THREAD

**Issue by PhilippvK** [PhilippvK/playforia-minigolf#73]
Cloning the repository on MacOS leads to:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tracks/tracks/AmazingRace.track'
  'tracks/tracks/Amazingrace.track'
  'tracks/tracks/BackandForth.track'
  'tracks/tracks/Backandforth.track'
  'tracks/tracks/HangOver.track'
  'tracks/tracks/Hangover.track'
  'tracks/tracks/JustGO.track'
  'tracks/tracks/Justgo.track'
  'tracks/tracks/SoNearSoFar.track'
  'tracks/tracks/Sonearsofar.track'
  'tracks/tracks/SwingAround.track'
  'tracks/tracks/Swingaround.track'
```

**Comment by PhilippvK** [comment]
@pehala Do you know if there "duplicated" already existed before your changes? It seems like they contain different information...

**Comment by pehala** [comment]
They seem like they did, it looks like they are from different creators

**Comment by pehala** [comment]
The tracks are different and won´t be overlap so I guess this is just a matter of renaming their files?

**Comment by PhilippvK** [comment]
So we just make the lower case version upper case and append f.e. a `2` to the filenames?

**Comment by PhilippvK** [comment]
I can rename them with `git mv -f` or just use Linux 😂

**Comment by pehala** [comment]
> 
> 
> So we just make the lower case version upper case and append f.e. a `2` to the filenames?

yes, the filenames are arbitrary.
