### ISSUE TITLE
Missing tracks

### ISSUE THREAD

**Issue by Nokkasiili** [PhilippvK/playforia-minigolf#89]
errors:
- [x] Aither-Four Rooms
- [x] Enygma-There and back
- [x] Zwan-Bridges
- [x] Leonardo-Divider
- [x] Dewlor-Epic Fail
- [x] Darwin-Too easy
- [x] Ennaji-Separated
- ~~fc-House of Fun~~

Removed some tracks from list that looked custom

**Comment by PhilippvK** [comment]
Almost every other week I find assets or tracks which never should have been in the game... Thanks for reporting.

**Comment by PhilippvK** [comment]
Somehow your Track Author names don't really match.

I locally removed the following:
- `Four Rooms ` from `tracks/sets/oakpark.trackset`
- `There and back` from `tracks/sets/onebyone.trackset`
- `Bridges` from `tracks/sets/tormentfields.trackset`
- `tracks/tracks/EpicFail.track`
- `tracks/tracks/Tooeasy.track`, `tracks/tracks/Tooeasytoo.track`, `tracks/tracks/EpicFail.track` and `Too easy too` from `tracks/sets/onebyone.trackset`
- `tracks/tracks/Separated.track`

Where do I find the following?
- `Leonardo-Divider`
- `fc-House of Fun`

I may also update `doc/tracksets.txt`...

**Comment by Nokkasiili** [comment]
There are 2 tracks with same name and they are most likely overwriten.
https://github.com/WorldStarHipHopX/playforia/blob/7a7e573a1688bf62f465173153f4936b27430be5/tracks/modern/Ennaji-Separated.track
https://github.com/WorldStarHipHopX/playforia/blob/7a7e573a1688bf62f465173153f4936b27430be5/tracks/modern/Tiikoni-Separated.track

**Comment by Nokkasiili** [comment]
> Somehow your Track Author names don't really match.
> 
> I locally removed the following:
> 

> I may also update `doc/tracksets.txt`...

I mean these are tracks are missing from this repo

**Comment by PhilippvK** [comment]
Well yes, because I removed the CUSTOM track category completely because it was full of inappropriate symbols and names...

**Comment by Nokkasiili** [comment]
> * `Leonardo-Divider`
https://github.com/WorldStarHipHopX/playforia/blob/7a7e573a1688bf62f465173153f4936b27430be5/tracks/modern/Leonardo-Divider.track
Overwritten by
https://github.com/PhilippvK/playforia-minigolf/blob/master/tracks/tracks/Divider.track
> * `fc-House of Fun`
this seems custom

**Comment by PhilippvK** [comment]
Thanks. Can you tell if there are other tracks which have been dropped due to removing the Author from the Tracks filename?

**Comment by Nokkasiili** [comment]
> Thanks. Can you tell if there are other tracks which have been dropped due to removing the Author from the Tracks filename?
All tracks that i listed in firstpost expect fc

**Comment by PhilippvK** [comment]
@pehala Would it be possible to reintroduce the Author name in the Tracks filenames? Do you have another idea to handle duplicate Track Names?

**Comment by pehala** [comment]
I assumed all the duplicates were, well, duplicates so I do not see much value in adding those in. If the original had wrong names and duplicates I would probably opt for manually adding them back in, because I believe systematic solutions won't work here.
