### ISSUE TITLE
How to use with IPv6 Network?

### ISSUE THREAD

**Issue by iZz0s** [PhilippvK/playforia-minigolf#91]
Hi,

just want to use that game with a friend but we cant port-forward through ipv6. any tips here?

**Comment by PhilippvK** [comment]
I have never tried out using the server with  an IPv6 IP.

Unfortunately I have no idea how to fix that but I leave this issue open...

**Comment by iZz0s** [comment]
hi,

the problem is that a lot of ISPs are using IPv6 and IPv4 Support with DS-Lite instead of Dual-Stack.

So i have problem to forward the port in my fritzbox, because my friend can't connect through my IPv4 IP over DS-Lite.

Unfortunately, he have a IPv6/IPv4 DS-Lite connection, too ^^

Fortunately, i have found a solution which was working great. We have played this legendary minigolf game through a VPN-Tunnel :)

this are legendary childhood memories, as we played it a lot of times at school and at home 10-12 years ago 🗡️ 

thanks for this contribute! :)

**Comment by PhilippvK** [comment]
@iZz0s Good news! Fixed in d2faaef7c562e76b0119d5718b463e375b5aae20

Can you rebuild the Client by yourself or do I need to release rebuild binaries?
The Server should work without patches.

**Comment by iZz0s** [comment]
hey i cant build myself but of course i can test the new client if it works then with ip v6.

**Comment by PhilippvK** [comment]
Thanks a lot your your good words :)

The VPN Tunnel approach also sounds nice and is probably more secure than the port forwarding but you should not need it anymore.

**Comment by PhilippvK** [comment]
@iZz0s Here is pre-release for you to try it out:

https://github.com/PhilippvK/playforia-minigolf/releases/tag/v2.1.2.0-BETA

Let me know if it works, I was only able to test it with localhost e.g. `::1`
